### ISSUE TITLE
GitHub action failure(s)

### ISSUE THREAD

**Issue by joeflack4** [monarch-initiative/omim#105]
## Overview
Not sure why, but it's failing to `pip install` even though the `requirements.txt` lists specific versions and has not changes.

## Error
Short err: `Collecting PyYAML==5.4.1 ... AttributeError: cython_sources`

[GH action log](https://github.com/monarch-initiative/omim/actions/runs/5633548760/job/15262916429)

<details><summary>Stacktrace</summary>
<p>

```
Collecting PyYAML==5.4.1
  Downloading PyYAML-5.4.1.tar.gz (175 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 175.1/175.1 KB 276.1 MB/s eta 0:00:00
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'error'
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [43 lines of output]
      running egg_info
      Traceback (most recent call last):
        File "/usr/lib/python3/dist-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
          main()
        File "/usr/lib/python3/dist-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/usr/lib/python3/dist-packages/pip/_vendor/pep517/in_process/_in_process.py", line 130, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/usr/lib/python3/dist-packages/setuptools/build_meta.py", line 162, in get_requires_for_build_wheel
          return self._get_build_requires(
        File "/usr/lib/python3/dist-packages/setuptools/build_meta.py", line [143](https://github.com/monarch-initiative/omim/actions/runs/5633548760/job/15262916429#step:4:144), in _get_build_requires
          self.run_setup()
        File "/usr/lib/python3/dist-packages/setuptools/build_meta.py", line 158, in run_setup
          exec(compile(code, __file__, 'exec'), locals())
        File "setup.py", line 271, in <module>
          setup(
        File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 153, in setup
          return distutils.core.setup(**attrs)
        File "/usr/lib/python3/dist-packages/setuptools/_distutils/core.py", line [148](https://github.com/monarch-initiative/omim/actions/runs/5633548760/job/15262916429#step:4:149), in setup
          return run_commands(dist)
        File "/usr/lib/python3/dist-packages/setuptools/_distutils/core.py", line [163](https://github.com/monarch-initiative/omim/actions/runs/5633548760/job/15262916429#step:4:164), in run_commands
          dist.run_commands()
        File "/usr/lib/python3/dist-packages/setuptools/_distutils/dist.py", line 967, in run_commands
          self.run_command(cmd)
        File "/usr/lib/python3/dist-packages/setuptools/_distutils/dist.py", line 986, in run_command
          cmd_obj.run()
        File "/usr/lib/python3/dist-packages/setuptools/command/egg_info.py", line 299, in run
          self.find_sources()
        File "/usr/lib/python3/dist-packages/setuptools/command/egg_info.py", line 306, in find_sources
          mm.run()
        File "/usr/lib/python3/dist-packages/setuptools/command/egg_info.py", line 541, in run
          self.add_defaults()
        File "/usr/lib/python3/dist-packages/setuptools/command/egg_info.py", line 578, in add_defaults
          sdist.add_defaults(self)
        File "/usr/lib/python3/dist-packages/setuptools/_distutils/command/sdist.py", line 228, in add_defaults
          self._add_defaults_ext()
        File "/usr/lib/python3/dist-packages/setuptools/_distutils/command/sdist.py", line 312, in _add_defaults_ext
          self.filelist.extend(build_ext.get_source_files())
        File "setup.py", line 201, in get_source_files
          self.cython_sources(ext.sources, ext)
        File "/usr/lib/python3/dist-packages/setuptools/_distutils/cmd.py", line 103, in __getattr__
          raise AttributeError(attr)
      AttributeError: cython_sources
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

</p>
</details>

**Comment by matentzn** [comment]
This is sometimes caused by a misatch of setuptools with some library. I would suggest either proper dependency management with poetry, including setup up a fresh dev environment each time, or at least upgrading pip and setuptools before running script.

**Comment by matentzn** [comment]
Is this really still an issue?

**Comment by joeflack4** [comment]
@matentzn Other than last week, as you know, I had been really strapped for monarch time, sorry about that. I can put this ahead of Medgen etc for now. Hopefully it is indeed a quick fix.

**Comment by matentzn** [comment]
This is not super important! My question was more: maybe it solved itself already! Such errors can be temporary!

**Comment by joeflack4** [comment]
Oh, I see. I felt bad. Yes it's still an issue. It's been failing for 3 weeks now I think. I'll continue to prioritize this after this next bit of Medgen conflict work that I'm going to try to finish this weekend then. I can bump it up too though.

**Comment by matentzn** [comment]
@hrshdhgd must have seen this error many times, maybe he has a quick idea?

**Comment by joeflack4** [comment]
Thanks Harshad. Probably that will fix it.

It's weird that the GitHub action didn't change and it suddenly started breaking.

**Comment by matentzn** [comment]
After some consideration and last weeks meeting: please prioritise this issue sometime soon!

**Comment by joeflack4** [comment]
@matentzn @sabrinatoro The OMIM GitHub action is fixed, so the next time the pipeline is up, it will be updated.

@hrshdhgd Thanks for the suggestion. Bumping PyYAML worked!
