### ISSUE TITLE
Cant run release myself

### ISSUE THREAD

**Issue by matentzn** [monarch-initiative/omim#38]
My Key works: I just tried downloading some file - so it must be that there are _some_ things it does not work for.

```
Loading .env environment variables...
RDFLib Version: 6.0.0
Trying to repaire malformed omim id: 147060,
Repaired malformed omim id: 147060
Trying to repaire malformed omim id: 150550,
Repaired malformed omim id: 150550
Trying to repaire malformed omim id: 270550,
Repaired malformed omim id: 270550
Trying to repaire malformed omim id: 190350,
Repaired malformed omim id: 190350
Trying to repaire malformed omim id: {607459}
Repaired malformed omim id: 607459
Have 26188 omim numbers from mimTitles.txt
Have 27524 total omim types 
Traceback (most recent call last):
  File "/Users/matentzn/opt/anaconda3/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Users/matentzn/opt/anaconda3/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/matentzn/ws/omim/omim2obo/__main__.py", line 8, in <module>
    cli()
  File "/Users/matentzn/ws/omim/omim2obo/interfaces/cli.py", line 42, in cli
    run(use_cache=kwargs.use_cache)
  File "/Users/matentzn/ws/omim/omim2obo/main.py", line 174, in run
    pheno_series = parse_phenotypic_series_titles(retrieve_mim_file('phenotypicSeries.txt', download_files_tf))
  File "/Users/matentzn/ws/omim/omim2obo/parsers/omim_txt_parser.py", line 45, in retrieve_mim_file
    raise RuntimeError(msg)
RuntimeError: Response from server: The entitlement requested is not available to this data account, please contact us at https://omim.org/contact if this is an issue
make: *** [build] Error 1
```

**Comment by joeflack4** [comment]
@matentzn I believe you said that your API_KEY now correctly downloads these, so I am closing. If I'm incorrect and you're still having issues, then (1) we should re-open this issue, (2) we should get you a working API_KEY, and (3) we should decide if, should this happen, we should fallback on the cache, or if throwing this error is indeed the correct action.
